// flow-typed signature: 1e79abeaf56157e262c01461f02153f7
// flow-typed version: <<STUB>>/fresh_v0.5.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fresh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fresh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fresh/index' {
  declare module.exports: $Exports<'fresh'>;
}
declare module 'fresh/index.js' {
  declare module.exports: $Exports<'fresh'>;
}
